### ISSUE TITLE
Command is aborted when executing a custom command

### ISSUE THREAD

**Issue by masabni** [ash-jc-allen/laravel-executor#6]
I'm trying to execute a custom command that prompts the user for info like this:
```
public function handle()
    {
          $email = $this->ask('Email')
          ....
```
and when it gets to this line its aborted
```
Email:
 >

  Aborted.
```
am I missing something? here's my executed code
```
public function run(): Executor
    {
        return $this->simpleDesktopNotification('Starting Executor', 'Starting the AppUpdate Executor.')
            ->runArtisan('passport:client --personal')
            ->runArtisan('setup:user')
            ->completeNotification();
    }
```

**Comment by ash-jc-allen** [comment]
Hi @masabni 

This package isn't really intended for interactive scripts like the one you've got there. It's intended more for triggering a bunch of scripts and leaving them to run on their own. In the same sort of way that you might run deployment scripts on a web server (like using Laravel Forge deploy scripts).

So with your current method, it probably won't work unfortunately. I'd be open to any pull requests though if you can think of a clean way of running these interactive scripts.

As an alternative, to get your script to run (if it's something that you are able to do), you could update your ``` setup:user ``` script to accept options and arguments. E.g. - ``` setup:user --email=youremail@domain.com ```.

Does any of this help at all? :smile:

**Comment by masabni** [comment]
@ash-jc-allen ok, no problem, I'll try to look for a solution and make a pr for this issue.

Thanks a lot for this package and appreciate your help.
